<a href="https://colab.research.google.com/github/idouba/AlgoXY/blob/algoxy/Linear_Regression_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [1]:
# @title
import torch
import numpy as np

## Data

In [3]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])


In [6]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


## Dataset

In [7]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets)

In [ ]:
dataset[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

## DataLoader

In [ ]:
from torch.utils.data import DataLoader

batch_size = 3
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [ ]:
# A Batch Sample
for inp,target in train_loader:
    print(inp)
    print(target)
    break

tensor([[101.,  44.,  37.],
        [ 74.,  66.,  43.],
        [103.,  43.,  36.]])
tensor([[21., 38.],
        [57., 69.],
        [20., 38.]])


## Linear Regression

In [ ]:
w = torch.randn(2, 3, requires_grad=True) #Weights
b = torch.randn(2, requires_grad=True) # Bias
print(w)
print(b)

tensor([[-0.1731, -0.6897,  0.3472],
        [-1.1402, -1.0512, -2.0045]], requires_grad=True)
tensor([ 0.0628, -1.0764], requires_grad=True)


In [ ]:
# Text classidication, lm etc
def model(X):
    return X @ w.t() + b

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[105.4609,  17.5877],
        [ 78.4351, -14.3465],
        [ 81.4131,   2.6698]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 82., 100.],
        [104., 118.],
        [118., 132.]])


### Loss

In [ ]:
def mse_loss(predictions, targets):
    difference = predictions - targets
    return torch.sum(difference * difference) / difference.numel()

# Mean: sum/count

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    print("\nLoss is: ",mse_loss(preds, y))
    break

Prediction is :
 tensor([[104.8198,  15.8515],
        [ 80.8309,  20.3012],
        [ 79.7868,   2.4079]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 80., 102.],
        [ 56.,  70.],
        [119., 133.]])

Loss is:  tensor(4952.6855, grad_fn=<DivBackward0>)


In [ ]:
epochs = 50
for i in range(epochs):
    # Iterate through training dataloader
    for x,y in train_loader:
        # Generate Prediction
        preds = model(x)
        # Get the loss and perform backpropagation
        loss = mse_loss(preds, y)
        loss.backward()
        # print(loss)
        # Let's update the weights
        with torch.no_grad():
            w -= w.grad * 1e-5 # w = w - w.grad * 0.00001
            b -= b.grad * 1e-5
            # Set the gradients to zero
            w.grad.zero_()
            b.grad.zero_()
    print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/50: Loss: 39.82994842529297
Epoch 1/50: Loss: 30.654478073120117
Epoch 2/50: Loss: 68.6048355102539
Epoch 3/50: Loss: 42.25682067871094
Epoch 4/50: Loss: 44.0922966003418
Epoch 5/50: Loss: 2.393836736679077
Epoch 6/50: Loss: 6.886496067047119
Epoch 7/50: Loss: 57.208736419677734
Epoch 8/50: Loss: 10.268721580505371
Epoch 9/50: Loss: 16.469043731689453
Epoch 10/50: Loss: 24.616241455078125
Epoch 11/50: Loss: 49.498809814453125
Epoch 12/50: Loss: 42.61131286621094
Epoch 13/50: Loss: 18.060483932495117
Epoch 14/50: Loss: 36.587711334228516
Epoch 15/50: Loss: 23.599815368652344
Epoch 16/50: Loss: 24.5932674407959
Epoch 17/50: Loss: 25.95461082458496
Epoch 18/50: Loss: 28.617746353149414
Epoch 19/50: Loss: 28.986486434936523
Epoch 20/50: Loss: 2.889214515686035
Epoch 21/50: Loss: 30.027376174926758
Epoch 22/50: Loss: 19.069189071655273
Epoch 23/50: Loss: 14.376457214355469
Epoch 24/50: Loss: 16.387975692749023
Epoch 25/50: Loss: 34.42115783691406
Epoch 26/50: Loss: 23.94528388977050

## Results

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[102.6596, 110.3845],
        [ 81.1419,  95.7303],
        [ 56.8479,  70.9188]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[103., 119.],
        [ 82., 100.],
        [ 56.,  70.]])
